runtime: nodejs18

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "YOUR_BACKEND_URL"
