steps:
  # Build the container image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/idkai-frontend:latest'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/idkai-frontend:latest'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/idkai-frontend:$BUILD_ID'
      - './frontend'
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/idkai-frontend'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'idkai-frontend'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/idkai-frontend:$BUILD_ID'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'

timeout: '1200s'

options:
  machineType: 'E2_HIGHCPU_8'
