steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/idkai-${_SERVICE_NAME}'
      - '-f'
      - '${_DOCKERFILE}'
      - '${_SOURCE_DIR}'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/idkai-${_SERVICE_NAME}'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'idkai-${_SERVICE_NAME}'
      - '--image=gcr.io/$PROJECT_ID/idkai-${_SERVICE_NAME}'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=${_PORT}'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=5'
    - '--timeout=900'
    - '--set-env-vars=GEMINI_API_KEY=${_GEMINI_API_KEY},GOOGLE_API_KEY=${_GOOGLE_API_KEY},DEPLOYED_BACKEND_URL=${_DEPLOYED_BACKEND_URL},DEPLOYED_FRONTEND_URL=${_DEPLOYED_FRONTEND_URL}'

# Build configuration
options:
  substitutionOption: 'ALLOW_LOOSE'

# Substitution variables (set when triggering build)
substitutions:
  _SERVICE_NAME: 'orchestrator'  # Default, override per service
  _SOURCE_DIR: '.'              # Default, override per service
  _DOCKERFILE: 'orchestrator/Dockerfile'  # Default Dockerfile
  _PORT: '8000'                 # Default, override per service
  _GEMINI_API_KEY: ''           # Must be set
  _GOOGLE_API_KEY: ''           # Optional
  _DEPLOYED_BACKEND_URL: ''     # Set to deployed orchestrator base URL
  _DEPLOYED_FRONTEND_URL: ''    # Set to deployed frontend base URL
